
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/nix/store/2xyd9pnqzg74a9xlayi54d2bcy1844n5-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:4 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/nix/store/5cfwmqmymsqynbyqq0vkbpf6914550x7-procps-4.0.6/bin/"
      - "/nix/store/ixsp81bia5w1fqd2d59vwbcfqk3n5231-ripgrep-15.1.0/bin/"
      - "/nix/store/zp6rsi809fx5h7dccn7aidg1mj8zgn52-bubblewrap-0.11.2/bin/"
      - "/nix/store/n50qh3qh69k1lqbd9ygkd5jar429ax82-socat-1.8.1.1/bin/"
      - "/nix/store/lfbzxs5wyqd2122mpbj5azkxhxspw9cd-bash-interactive-5.3p3/bin/"
      - "/nix/store/5mrhn7sj5hmx1sqqj1568sya450yarvx-patchelf-0.15.2/bin/"
      - "/nix/store/8v97ngkcpfzgghwnnr7fsz33p2x22gy9-gcc-wrapper-14.3.0/bin/"
      - "/nix/store/ipr6y28viyqkhkg58rdvy27m01q5j5nh-gcc-14.3.0/bin/"
      - "/nix/store/6s5jp0cchd4jjq474xkfymj18l6i5x95-glibc-2.40-224-bin/bin/"
      - "/nix/store/hqkszxk2c0cxvd04xa4gsaqs182dw8l2-coreutils-9.8/bin/"
      - "/nix/store/iz5lckcsg66r223si2gck7csk2hihj0m-binutils-wrapper-2.44/bin/"
      - "/nix/store/i7mdvmliqcb5lz0nqija8rq55vws6gi8-binutils-2.44/bin/"
      - "/nix/store/2xyd9pnqzg74a9xlayi54d2bcy1844n5-cmake-4.1.2/bin/"
      - "/nix/store/8xhaz2ysixijy8sgzmwmhlialqqind1p-findutils-4.10.0/bin/"
      - "/nix/store/cw3a3yz8vrfsz53ypjw8hspy5hzzx2py-diffutils-3.12/bin/"
      - "/nix/store/4zi0y6cmpjnbhmgrx7vfgqkyv5z1z4z0-gnused-4.9/bin/"
      - "/nix/store/k3wiv3qqa4y0im5v1iq2jy4h9cm32dfc-gnugrep-3.12/bin/"
      - "/nix/store/88d79vz87a5g3wsclabrgqd93jqh5yv8-gawk-5.3.2/bin/"
      - "/nix/store/xl6pd2spjajwcpq09fnmnjv5psqmlmma-gnutar-1.35/bin/"
      - "/nix/store/rhp8ph1q699irvmacp27x3sw84slk32i-gzip-1.14/bin/"
      - "/nix/store/g36v1ss2ywkqp751wlkhnd8n9zaqkg2w-bzip2-1.0.8-bin/bin/"
      - "/nix/store/djjc508wnfdwmkv5xrxxqx5r2v09yxfp-gnumake-4.4.1/bin/"
      - "/nix/store/3hgg7pr65imdrifqqh3flg3arvkc2r22-bash-5.3p3/bin/"
      - "/nix/store/wgnxx41q3d2cx6j5wk2s5bkjyzrr3ggn-patch-2.8/bin/"
      - "/nix/store/3x3p3mhwn18q7qplxn34i13rdmswi0qm-xz-5.8.3-bin/bin/"
      - "/nix/store/018l43lbsqbrsasrfdcxxb5s4s161fkr-file-5.45/bin/"
      - "/nix/store/k48xvnfrv6wzjk81vfmnqrsfvbbvjl0v-vcpkg-2025.10.17/bin/"
      - "/run/wrappers/bin/"
      - "/home/bobi/.local/share/flatpak/exports/bin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/home/bobi/.nix-profile/bin/"
      - "/nix/profile/bin/"
      - "/home/bobi/.local/state/nix/profile/bin/"
      - "/etc/profiles/per-user/bobi/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/run/current-system/sw/bin/"
      - "/nix/store/lwyzzfsckz3lbczrd9mqm51h5m78q33a-ghostty-1.3.1/bin/"
    searched_directories:
      - "/nix/store/5cfwmqmymsqynbyqq0vkbpf6914550x7-procps-4.0.6/bin/uname"
      - "/nix/store/ixsp81bia5w1fqd2d59vwbcfqk3n5231-ripgrep-15.1.0/bin/uname"
      - "/nix/store/zp6rsi809fx5h7dccn7aidg1mj8zgn52-bubblewrap-0.11.2/bin/uname"
      - "/nix/store/n50qh3qh69k1lqbd9ygkd5jar429ax82-socat-1.8.1.1/bin/uname"
      - "/nix/store/lfbzxs5wyqd2122mpbj5azkxhxspw9cd-bash-interactive-5.3p3/bin/uname"
      - "/nix/store/5mrhn7sj5hmx1sqqj1568sya450yarvx-patchelf-0.15.2/bin/uname"
      - "/nix/store/8v97ngkcpfzgghwnnr7fsz33p2x22gy9-gcc-wrapper-14.3.0/bin/uname"
      - "/nix/store/ipr6y28viyqkhkg58rdvy27m01q5j5nh-gcc-14.3.0/bin/uname"
      - "/nix/store/6s5jp0cchd4jjq474xkfymj18l6i5x95-glibc-2.40-224-bin/bin/uname"
    found: "/nix/store/hqkszxk2c0cxvd04xa4gsaqs182dw8l2-coreutils-9.8/bin/uname"
    search_context:
      ENV{PATH}:
        - "/nix/store/5cfwmqmymsqynbyqq0vkbpf6914550x7-procps-4.0.6/bin"
        - "/nix/store/ixsp81bia5w1fqd2d59vwbcfqk3n5231-ripgrep-15.1.0/bin"
        - "/nix/store/zp6rsi809fx5h7dccn7aidg1mj8zgn52-bubblewrap-0.11.2/bin"
        - "/nix/store/n50qh3qh69k1lqbd9ygkd5jar429ax82-socat-1.8.1.1/bin"
        - "/nix/store/lfbzxs5wyqd2122mpbj5azkxhxspw9cd-bash-interactive-5.3p3/bin"
        - "/nix/store/5mrhn7sj5hmx1sqqj1568sya450yarvx-patchelf-0.15.2/bin"
        - "/nix/store/8v97ngkcpfzgghwnnr7fsz33p2x22gy9-gcc-wrapper-14.3.0/bin"
        - "/nix/store/ipr6y28viyqkhkg58rdvy27m01q5j5nh-gcc-14.3.0/bin"
        - "/nix/store/6s5jp0cchd4jjq474xkfymj18l6i5x95-glibc-2.40-224-bin/bin"
        - "/nix/store/hqkszxk2c0cxvd04xa4gsaqs182dw8l2-coreutils-9.8/bin"
        - "/nix/store/iz5lckcsg66r223si2gck7csk2hihj0m-binutils-wrapper-2.44/bin"
        - "/nix/store/i7mdvmliqcb5lz0nqija8rq55vws6gi8-binutils-2.44/bin"
        - "/nix/store/2xyd9pnqzg74a9xlayi54d2bcy1844n5-cmake-4.1.2/bin"
        - "/nix/store/hqkszxk2c0cxvd04xa4gsaqs182dw8l2-coreutils-9.8/bin"
        - "/nix/store/8xhaz2ysixijy8sgzmwmhlialqqind1p-findutils-4.10.0/bin"
        - "/nix/store/cw3a3yz8vrfsz53ypjw8hspy5hzzx2py-diffutils-3.12/bin"
        - "/nix/store/4zi0y6cmpjnbhmgrx7vfgqkyv5z1z4z0-gnused-4.9/bin"
        - "/nix/store/k3wiv3qqa4y0im5v1iq2jy4h9cm32dfc-gnugrep-3.12/bin"
        - "/nix/store/88d79vz87a5g3wsclabrgqd93jqh5yv8-gawk-5.3.2/bin"
        - "/nix/store/xl6pd2spjajwcpq09fnmnjv5psqmlmma-gnutar-1.35/bin"
        - "/nix/store/rhp8ph1q699irvmacp27x3sw84slk32i-gzip-1.14/bin"
        - "/nix/store/g36v1ss2ywkqp751wlkhnd8n9zaqkg2w-bzip2-1.0.8-bin/bin"
        - "/nix/store/djjc508wnfdwmkv5xrxxqx5r2v09yxfp-gnumake-4.4.1/bin"
        - "/nix/store/3hgg7pr65imdrifqqh3flg3arvkc2r22-bash-5.3p3/bin"
        - "/nix/store/wgnxx41q3d2cx6j5wk2s5bkjyzrr3ggn-patch-2.8/bin"
        - "/nix/store/3x3p3mhwn18q7qplxn34i13rdmswi0qm-xz-5.8.3-bin/bin"
        - "/nix/store/018l43lbsqbrsasrfdcxxb5s4s161fkr-file-5.45/bin"
        - "/nix/store/lfbzxs5wyqd2122mpbj5azkxhxspw9cd-bash-interactive-5.3p3/bin"
        - "/nix/store/5mrhn7sj5hmx1sqqj1568sya450yarvx-patchelf-0.15.2/bin"
        - "/nix/store/8v97ngkcpfzgghwnnr7fsz33p2x22gy9-gcc-wrapper-14.3.0/bin"
        - "/nix/store/ipr6y28viyqkhkg58rdvy27m01q5j5nh-gcc-14.3.0/bin"
        - "/nix/store/6s5jp0cchd4jjq474xkfymj18l6i5x95-glibc-2.40-224-bin/bin"
        - "/nix/store/hqkszxk2c0cxvd04xa4gsaqs182dw8l2-coreutils-9.8/bin"
        - "/nix/store/iz5lckcsg66r223si2gck7csk2hihj0m-binutils-wrapper-2.44/bin"
        - "/nix/store/i7mdvmliqcb5lz0nqija8rq55vws6gi8-binutils-2.44/bin"
        - "/nix/store/k48xvnfrv6wzjk81vfmnqrsfvbbvjl0v-vcpkg-2025.10.17/bin"
        - "/nix/store/hqkszxk2c0cxvd04xa4gsaqs182dw8l2-coreutils-9.8/bin"
        - "/nix/store/8xhaz2ysixijy8sgzmwmhlialqqind1p-findutils-4.10.0/bin"
        - "/nix/store/cw3a3yz8vrfsz53ypjw8hspy5hzzx2py-diffutils-3.12/bin"
        - "/nix/store/4zi0y6cmpjnbhmgrx7vfgqkyv5z1z4z0-gnused-4.9/bin"
        - "/nix/store/k3wiv3qqa4y0im5v1iq2jy4h9cm32dfc-gnugrep-3.12/bin"
        - "/nix/store/88d79vz87a5g3wsclabrgqd93jqh5yv8-gawk-5.3.2/bin"
        - "/nix/store/xl6pd2spjajwcpq09fnmnjv5psqmlmma-gnutar-1.35/bin"
        - "/nix/store/rhp8ph1q699irvmacp27x3sw84slk32i-gzip-1.14/bin"
        - "/nix/store/g36v1ss2ywkqp751wlkhnd8n9zaqkg2w-bzip2-1.0.8-bin/bin"
        - "/nix/store/djjc508wnfdwmkv5xrxxqx5r2v09yxfp-gnumake-4.4.1/bin"
        - "/nix/store/3hgg7pr65imdrifqqh3flg3arvkc2r22-bash-5.3p3/bin"
        - "/nix/store/wgnxx41q3d2cx6j5wk2s5bkjyzrr3ggn-patch-2.8/bin"
        - "/nix/store/3x3p3mhwn18q7qplxn34i13rdmswi0qm-xz-5.8.3-bin/bin"
        - "/nix/store/018l43lbsqbrsasrfdcxxb5s4s161fkr-file-5.45/bin"
        - "/run/wrappers/bin"
        - "/home/bobi/.local/share/flatpak/exports/bin"
        - "/var/lib/flatpak/exports/bin"
        - "/home/bobi/.nix-profile/bin"
        - "/nix/profile/bin"
        - "/home/bobi/.local/state/nix/profile/bin"
        - "/etc/profiles/per-user/bobi/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/run/current-system/sw/bin"
        - "/nix/store/lwyzzfsckz3lbczrd9mqm51h5m78q33a-ghostty-1.3.1/bin"
...
